<a href="https://colab.research.google.com/github/Sahil-Tamrakar/Computational-Linguistic-Natural-Language-Processing-LAB/blob/main/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Experiment-5: Subword Level Tokenization and POS Tagging**

In [1]:
# Install Hugging Face Transformers, SentencePiece, and spaCy assets
!pip install -q transformers sentencepiece spacy nltk pandas tabulate
!python -m spacy download en_core_web_sm -q

import nltk
nltk.download('averaged_perceptron_tagger', quiet=True)
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

from google.colab import files
import pandas as pd

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 108.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
print("Upload your input text file (e.g., input.txt or dataset file):")
uploaded_5 = files.upload()
filename_5 = list(uploaded_5.keys())[0]

with open(filename_5, 'r', encoding='utf-8', errors='ignore') as f:
    text_data_5 = f.read().strip()

print(f"\nFile '{filename_5}' loaded successfully ({len(text_data_5)} characters).")

Upload your input text file (e.g., input.txt or dataset file):

Saving input_sub_word_data.txt to input_sub_word_data.txt

File 'input_sub_word_data.txt' loaded successfully (6682 characters).

Experiment 5.1: BPE Subword Tokenization
5.1 (a) Using Pretrained BPE Tokenizer (GPT-2)

In [3]:
from transformers import AutoTokenizer
import pandas as pd

# Load pretrained GPT-2 tokenizer (uses BPE)
bpe_tokenizer = AutoTokenizer.from_pretrained("gpt2")

# Tokenize input text
tokens_51a = bpe_tokenizer.tokenize(text_data_5)
token_ids_51a = bpe_tokenizer.convert_tokens_to_ids(tokens_51a)

# Display tokens and IDs
df_51a = pd.DataFrame({'Token': tokens_51a, 'Token ID': token_ids_51a})
print("=== 5.1 (a) BPE TOKENIZATION (PRETRAINED GPT-2) ===")
display(df_51a.head(20))  # Displaying first 20 tokens

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1348 > 1024). Running this sequence through the model will result in indexing errors

=== 5.1 (a) BPE TOKENIZATION (PRETRAINED GPT-2) ===

            Token  Token ID
0         Natural     35364
1       Ġlanguage      3303
2     Ġprocessing      7587
3             Ġis       318
4              Ġa       257
5         Ġbranch      8478
6             Ġof       286
7     Ġartificial     11666
8   Ġintelligence      4430
9           Ġthat       326
10              Ċ       198
11             en       268
12          ables      2977
13     Ġcomputers      9061
14            Ġto       284
15    Ġunderstand      1833
16              ,        11
17     Ġinterpret      6179
18              ,        11
19           Ġand       290

5.1 (b) BPE Tokenizer Trained from Scratch (Without Pretrained Model)

In [4]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers
import pandas as pd

# 1. Save text to temporary file for training
with open("temp_bpe_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_data_5)

# 2. Initialize a BPE Model from scratch
tokenizer_scratch = Tokenizer(models.BPE())
tokenizer_scratch.pre_tokenizer = pre_tokenizers.Whitespace()

# 3. Train BPE model on your custom dataset file
trainer = trainers.BpeTrainer(vocab_size=1000, special_tokens=["[PAD]", "[UNK]"])
tokenizer_scratch.train(files=["temp_bpe_corpus.txt"], trainer=trainer)

# 4. Tokenize text
encoding = tokenizer_scratch.encode(text_data_5)

# Display generated tokens and IDs
df_51b = pd.DataFrame({'Token': encoding.tokens, 'Token ID': encoding.ids})
print("=== 5.1 (b) BPE TOKENIZATION (TRAINED FROM SCRATCH) ===")
display(df_51b.head(20))

=== 5.1 (b) BPE TOKENIZATION (TRAINED FROM SCRATCH) ===

           Token  Token ID
0        Natural       356
1       language       139
2     processing       189
3             is        79
4              a        21
5         branch       875
6             of        86
7     artificial       921
8   intelligence       919
9           that       263
10       enables       914
11     computers       839
12            to        59
13    understand       214
14             ,         2
15     interpret       916
16             ,         2
17           and        70
18      generate       810
19         human       890

Experiment 5.2: SentencePiece Tokenization
5.2 (a) Using Pretrained SentencePiece Tokenizer (ALBERT / XLNet)

In [5]:
from transformers import AutoTokenizer
import pandas as pd

# Load pretrained ALBERT tokenizer (uses SentencePiece)
sp_pretrained = AutoTokenizer.from_pretrained("albert-base-v2")

# Tokenize text
tokens_52a = sp_pretrained.tokenize(text_data_5)
token_ids_52a = sp_pretrained.convert_tokens_to_ids(tokens_52a)

# Display tokens and IDs
df_52a = pd.DataFrame({'Token': tokens_52a, 'Token ID': token_ids_52a})
print("=== 5.2 (a) SENTENCEPIECE TOKENIZATION (PRETRAINED ALBERT) ===")
display(df_52a.head(20))

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (1275 > 512). Running this sequence through the model will result in indexing errors

=== 5.2 (a) SENTENCEPIECE TOKENIZATION (PRETRAINED ALBERT) ===

            Token  Token ID
0        ▁natural      1112
1       ▁language       816
2     ▁processing      5511
3             ▁is        25
4              ▁a        21
5         ▁branch      1686
6             ▁of        16
7     ▁artificial      6809
8   ▁intelligence      2872
9           ▁that        30
10       ▁enables     14645
11     ▁computers      7774
12            ▁to        20
13    ▁understand      1369
14              ,        15
15     ▁interpret     11584
16              ,        15
17           ▁and        17
18      ▁generate      7920
19         ▁human       585

5.2 (b) SentencePiece Tokenizer Trained from Scratch

In [6]:
import sentencepiece as spm
import pandas as pd

# 1. Save input text for SentencePiece training
with open("sp_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_data_5)

# 2. Train SentencePiece model from scratch
spm.SentencePieceTrainer.train(
    input='sp_corpus.txt',
    model_prefix='custom_sp',
    vocab_size=min(500, len(set(text_data_5.split())) + 20),
    model_type='unigram'
)

# 3. Load trained model
sp = spm.SentencePieceProcessor()
sp.load('custom_sp.model')

# 4. Tokenize text
tokens_52b = sp.encode_as_pieces(text_data_5)
token_ids_52b = sp.encode_as_ids(text_data_5)

# Display tokens and IDs
df_52b = pd.DataFrame({'Token': tokens_52b, 'Token ID': token_ids_52b})
print("=== 5.2 (b) SENTENCEPIECE TOKENIZATION (FROM SCRATCH) ===")
display(df_52b.head(20))

=== 5.2 (b) SENTENCEPIECE TOKENIZATION (FROM SCRATCH) ===

          Token  Token ID
0      ▁Natural       177
1     ▁language        19
2   ▁processing        39
3           ▁is        16
4            ▁a         9
5            ▁b       292
6           ran       406
7            ch       146
8           ▁of        11
9         ▁arti       317
10          fic       143
11          ial       423
12        ▁inte       330
13           ll       273
14           ig       402
15         ence       156
16        ▁that        78
17          ▁en       149
18         able        67
19            s         6

Experiment 5.3: POS Tagging on Given Sentence
5.3 (a) POS Tagging using spaCy

In [7]:
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")
sentence_53 = "The young student is reading an interesting book in the library."

doc = nlp(sentence_53)

pos_spacy = []
for token in doc:
    pos_spacy.append({
        'Token': token.text,
        'POS Tag': token.pos_,
        'Description': spacy.explain(token.pos_)
    })

df_53a = pd.DataFrame(pos_spacy).drop_duplicates(subset=['Token'])
print("=== 5.3 (a) POS TAGGING (SPACY) ===")
display(df_53a)

=== 5.3 (a) POS TAGGING (SPACY) ===

          Token POS Tag  Description
0           The     DET   determiner
1         young     ADJ    adjective
2       student    NOUN         noun
3            is     AUX    auxiliary
4       reading    VERB         verb
5            an     DET   determiner
6   interesting     ADJ    adjective
7          book    NOUN         noun
8            in     ADP   adposition
9           the     DET   determiner
10      library    NOUN         noun
11            .   PUNCT  punctuation

5.3 (b) POS Tagging using NLTK

In [10]:
import nltk
nltk.download('tagsets_json', quiet=True)
from nltk.tokenize import word_tokenize
import pandas as pd

sentence_53 = "The young student is reading an interesting book in the library."

# Tokenize and Tag
tokens = word_tokenize(sentence_53)
tagged = nltk.pos_tag(tokens)

# NLTK POS Tag descriptions
nltk_pos_descriptions = {
    'DT': 'Determiner',
    'JJ': 'Adjective',
    'NN': 'Noun, singular or mass',
    'VBZ': 'Verb, 3rd person singular present',
    'VBG': 'Verb, gerund or present participle',
    'IN': 'Preposition or subordinating conjunction',
    '.': 'Punctuation mark'
}

pos_nltk = []
for token, tag in tagged:
    desc = nltk_pos_descriptions.get(tag, nltk.help.upenn_tagset(tag))
    pos_nltk.append({
        'Token': token,
        'POS Tag': tag,
        'Description': desc
    })

df_53b = pd.DataFrame(pos_nltk).drop_duplicates(subset=['Token'])
print("=== 5.3 (b) POS TAGGING (NLTK) ===")
display(df_53b)

DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
.: sentence terminator
    . ! ?
=== 5.3 (b) POS TAGGING (NLTK) ===

          Token POS Tag                               Description
0           The      DT                                Determiner
1         young      JJ                                 Adjective
2       student      NN                    Noun, singular or mass
3            is     VBZ         Verb, 3rd person singular present
4       reading     VBG        Verb, gerund or present participle
5            an      DT                                Determiner
6   interesting      JJ                                 Adjective
7          book      NN                    Noun, singular or mass
8            in      IN  Preposition or subordinating conjunction
9           the      DT                                Determiner
10      library      NN                    Noun, singular or mass
11            .       .                          Punctuation mark

Experiment 5.4: POS Tagging with Frequency Analysis (spaCy)

In [11]:
import spacy
from collections import Counter
import pandas as pd

nlp = spacy.load("en_core_web_sm")

# Process uploaded text from 5.1
doc_54 = nlp(text_data_5)

# Count frequencies of unique tokens (ignoring whitespace/newlines)
valid_tokens = [token.text.lower() for token in doc_54 if not token.is_space]
token_frequencies = Counter(valid_tokens)

# Extract unique token attributes
pos_54_data = []
seen_tokens = set()

for token in doc_54:
    token_lower = token.text.lower()
    if not token.is_space and token_lower not in seen_tokens:
        seen_tokens.add(token_lower)
        pos_54_data.append({
            'Unique Token': token.text,
            'POS Tag': token.pos_,
            'Description': spacy.explain(token.pos_),
            'Frequency': token_frequencies[token_lower]
        })

df_54 = pd.DataFrame(pos_54_data).sort_values(by='Frequency', ascending=False).reset_index(drop=True)

print("=== EXPERIMENT 5.4: POS TAGGING & FREQUENCY ANALYSIS (SPACY) ===")
display(df_54.head(25)) # Displays top 25 unique tokens

=== EXPERIMENT 5.4: POS TAGGING & FREQUENCY ANALYSIS (SPACY) ===

    Unique Token POS Tag               Description  Frequency
0              ,   PUNCT               punctuation         76
1              .   PUNCT               punctuation         65
2            the     DET                determiner         48
3              a     DET                determiner         28
4            and   CCONJ  coordinating conjunction         27
5            can     AUX                 auxiliary         23
6             of     ADP                adposition         22
7        subword    NOUN                      noun         17
8             be     AUX                 auxiliary         15
9             to    PART                  particle         15
10            is     AUX                 auxiliary         14
11          Word     ADJ                 adjective         13
12            as     ADP                adposition         13
13           BPE   PROPN               proper noun         13
14      language    NOUN                      noun         12
15             -   PUNCT               punctuation         11
16         units    NOUN                      noun         11
17     tokenizer    NOUN                      noun         11
18         words    NOUN                      noun         11
19        corpus    NOUN                      noun         10
20    vocabulary    NOUN                      noun         10
21           may     AUX                 auxiliary          9
22        tokens    NOUN                      noun          9
23           For     ADP                adposition          8
24  Tokenization   PROPN               proper noun          8